fingerprint: remove obsolete quirk.
mer-hybris/droid-hal-configs pull request #208
Opened 2021-01-28 12:40 UTC by krnlyng

[fingerprint] Remove obsolete quirk. JB#52758

The quirk has been reverted from the sailfish-fpd repository
and has been replaced with a proper fix for the issue.

2021-01-28 14:50 UTC, mlehtima approved these changes

2021-01-29 08:33 UTC, sledges commented
Please format your commit message to be more kernel.org-esque:)
```
fingerprint: remove obsolete quirk

The quirk has been reverted from the sailfish-fpd repository
and has been replaced with a proper fix for the issue.

[fingerprint] Remove obsolete quirk. JB#52758
```

2021-02-03 09:00 UTC, sledges requested changes
As per comment above

2021-02-09 08:47 UTC, sledges approved these changes

2021-03-05 18:07 UTC, merged