sparse-9: Add Android 9 generic sparse
mer-hybris/droid-hal-configs pull request #211
Opened 2021-02-08 13:57 UTC by Thaodan

2021-02-28 21:45 UTC, sledges requested changes

2021-02-28 21:45 UTC, sledges commented on sparse-9/etc/usb-moded/usb-moded-configfs.ini
> +[configfs]
This file is device-specific (e.g. Xperia 10 doesn't have this).

2022-02-01 06:16 UTC, Thaodan commented
@sledges Should we still merge this?

2022-02-01 09:38 UTC, sledges commented
Well @jusa is still not convinced, although monich [said](https://github.com/mer-hybris/droid-hal-configs/pull/246#issuecomment-1025410915) that this does make certain amount of sense:) (as default/fallback set of configs for fresh ports).

IMHO, it doesn't affect/break Xperia 10 (ganges) which is on Android 9, and we won't have time to migrate it to sparse-9, but would certainly help for any new/old community android-9 ports coming in.

2022-02-01 09:54 UTC, Thaodan commented
> Well @jusa is still not convinced, although monich
> [said](https://github.com/mer-hybris/droid-hal-configs/pull/246#issuecommen
> t-1025410915) that this does make certain amount of sense:) (as
> default/fallback set of configs for fresh ports).
That's the idea.
> IMHO, it doesn't affect/break Xperia 10 (ganges) which is on Android 9, and
> we won't have time to migrate it to sparse-9, but would certainly help for
> any new/old community android-9 ports coming in.
>

I pretty much agree we don't know what BSP a new port might use.

2022-12-15 08:30 UTC, saukko commented
Agreed not to do this for now.

2022-12-15 08:30 UTC, closed without merging