sparse: Move sysctl files to /usr/lib
mer-hybris/droid-hal-configs pull request #248
Opened 2022-02-01 06:10 UTC by Thaodan

sysctl files should go to /usr/lib similar to other files like oneshot
scripts or rpm macros.

2022-02-01 09:19 UTC, sledges requested changes
Worth mentioning that you also added sysusers.d in the commit description (which otherwise mainly talks only about sysctl.d).

2022-02-01 09:19 UTC, sledges commented on droid-configs.inc
> +    "sysusers.d"
Sorted:
```suggestion
    "sysctl.d"
    "systemd/system"
    "systemd/user"
    "sysusers.d"
    "tmpfiles.d"
```
P.S. This list is only for devices that are changing their adaptations from 32 to 64bit, but it's good to keep it updated as reference manual still.

2022-02-01 11:43 UTC, sledges approved these changes

2022-02-08 09:05 UTC, mkosola approved these changes

2022-02-08 09:07 UTC, merged